version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ergo
    main: ./cmd/ergo
    binary: ergo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

brews:
  - name: ergo
    homepage: https://github.com/sandover/ergo
    description: Minimal multi-agent DAG task planner built on an append-only JSONL event log
    license: MIT
    repository:
      owner: sandover
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
