version: '3'

vars:
  VERSION:
    sh: git describe --tags --always --dirty
  GOLANGCI_LINT_VERSION: v1.64.8

tasks:
  default:
    cmds:
      - task: install

  install:
    desc: Install ergo globally to $GOPATH/bin
    cmds:
      - go install -ldflags "-X main.version={{.VERSION}}" ./cmd/ergo
      - echo "Installed ergo {{.VERSION}}"

  build:
    desc: Build binary locally to ./bin/ergo
    cmds:
      - mkdir -p bin
      - go build -ldflags "-X main.version={{.VERSION}}" -o bin/ergo ./cmd/ergo

  run:
    desc: Run ergo from source (pass args like 'task run -- list')
    cmds:
      - go run ./cmd/ergo {{.CLI_ARGS}}

  test:
    desc: Run all tests with race detection
    cmds:
      - go test -race ./...

  cover:
    desc: Run tests with coverage report
    cmds:
      - go test -race -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

  bench:
    desc: Run performance benchmarks
    cmds:
      - go test -bench=. -benchmem ./...

  fmt:
    desc: Format all Go code
    cmds:
      - gofmt -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint (pinned version)
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}} run ./...

  clean:
    desc: Remove build artifacts and temporary files
    cmds:
      - rm -rf bin/ dist/ coverage.out
